# -*- coding: utf-8 -*-
"""Github_Language.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqHXu9yjf2CpkOFapY6bdKXzUPAJcI14
"""

import requests
from collections import defaultdict
import time

# Replace with your GitHub username
username = "yadavkapil23"

# GitHub API URL to list user's repos
repos_url = f"https://api.github.com/users/yadavkapil23/repos"
repos = []
page = 1

while True:
    resp = requests.get(repos_url, params={"per_page": 100, "page": page})
    data = resp.json()
    if not data:
        break
    repos.extend(data)
    page += 1
    # To be safe against rate limits, add a slight delay
    time.sleep(1)

language_totals = defaultdict(int)

for repo in repos:
    lang_url = repo["languages_url"]
    lang_data = requests.get(lang_url).json()
    for lang, bytes_count in lang_data.items():
        language_totals[lang] += bytes_count
    # Delay between requests to avoid rate limiting
    time.sleep(1)

total_bytes = sum(language_totals.values())
print("\nLanguage usage breakdown:")

for lang, count in sorted(language_totals.items(), key=lambda x: x[1], reverse=True):
    percent = (count / total_bytes) * 100
    print(f"{lang}: {percent:.2f}%")

